plugins:
  - jekyll-theme-hamilton

remote_theme:  ngzhio/jekyll-theme-hamilton

skin: midnight
title: Music Catalog
author: Kelsey Neis
email: garmoshka.chornaya@gmail.com
location: Minneapolis, MN
subscribe: false
